#%RAML 1.0
title: Help To Save
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include docs/versioning.md
 - title: E2E Live Support Journey Analysis
   content: !include docs/liveSupport.md
 - title: Timeouts
   content: !include docs/timeouts.md
 - title: Access to the API
   content: !include docs/access.md
 - title: Security Matters
   content: !include docs/security.md
 - title: Post Create Account end point
   content: !include docs/postCreateAccount.md
 - title: Get Eligibility Check end point
   content: !include docs/getEligibilityCheck.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/individuals/help-to-save/account:
  post:
    description: Sends a request to create an account on behalf of the user, noting the value fields below are all example values with the exception of fields Accept and Content-Type which should be presented as quoted string values as shown. For further information on field formats and examples, please see https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide, noting the timezone should be a UTC offset as outlined in the righthand column at https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations
    is: [headers.acceptHeader, headers.contentHeader]
    securedBy: [ sec.x-application ]
    headers:
      gov-client-user-ID:
        example: EL079651A
        description: Applicant's NINO
      gov-client-timezone:
         example: UTC
         description: Timezone Abbreviation
      gov-vendor-version:
         example: "1.3"
         description: Gov Vendor Version
      gov-vendor-instance-ID:
         example: fa7c484c-d8cf-4f8a-a39c-54a2a4c04bc6
         description: Hashed value, unique to a specific installation of the vendor's software
    body:
      application/json:
        type: !include schemas/CreateAccount.json
        example: !include schemas/CreateAccountExample.json
    responses:
      201:
      400:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Bad request http response
            example: !include examples/ErrorResponseExample.json
      401:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Unauthorized http response
            example: !include examples/ErrorUnauthorizedResponseExample.json
      403:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Forbidden http response
            example: !include examples/ErrorForbiddenResponseExample.json
      404:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Not found http response
            example: !include examples/ErrorNotFoundResponseExample.json
      405:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Method not allowed http response
            example: !include examples/ErrorMethodNotAllowedResponseExample.json
      409:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Conflict http response
            example: !include examples/ErrorConflictResponseExample.json
      500:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Internal server error response
            example: !include examples/InternalServerErrorResponseExample.json
      502:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Bad gateway http repsonse
            example: !include examples/BadGatewayErrorResponseExample.json
      503:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Service unavailable http response
            example: !include examples/ServiceUnavailableErrorResponseExample.json

/individuals/help-to-save/eligibility/[NINO]:
  get:
    description: Sends a request to check the eligibility of an applicant on behalf of the user, also checks if the applicant already has an account
    is: [headers.acceptHeader]
    securedBy: [ sec.x-application ]
    headers:
      Authorization:
       description: bearer [SERVER-TOKEN]
      Gov-Client-Public-IP:
        description: The IP of the server making the API call (can be a non-routable internal datacentre IP)
      Gov-Client-Public-port:
        description: The port of the server making the API call
      Gov-Client-Device-ID:
        description: This can be the MAC address of the network interface on the server making the API call
      Gov-Client-User-ID:
        description: The taxpayer's NINO (or other, more relevant tax identifier if this is not applicable)
      Gov-Client-Timezone:
        description: The timezone of the server making the API call
      Gov-Client-Local-IP:
        description: The IP of the server making the API call (can be a non-routable internal datacentre IP)
      Gov-Client-User-Agent:
        example: Windows Server/2016 (Dell PowerEgde R6415)
        description: The user agent of the server making the API call
      Gov-Vendor-Version:
        description: The version of the software making the API call
      Gov-Vendor-Instance-ID:
        example: app-server-1
        description: An identifier to differentiate between the various server instances
      Gov-Vendor-Public-IP:
        description: The IP of the server making the API call (can be a non-routable internal datacentre IP)
    responses:
      200:
        body:
          application/json:
            type: !include schemas/HappyEligibilityResponse.json
            examples:
              example-1:
                description: The person is eligible for Help to Save as they are entitled to WTC and in receipt of positive WTC/CTC Tax Credit and in receipt of UC and their household income is sufficient
                value: !include examples/EligiblePositiveWTCAndUCEligibilityResponseExample.json
              example-2:
                description: The person is eligible for Help to Save as they are in receipt of UC and their household income is sufficient
                value: !include examples/EligibleUCEligibilityResponseExample.json
              example-3:
                description: The person is eligible for Help to Save as they are entitled to WTC and in receipt of positive WTC/CTC Tax Credit
                value: !include examples/EligibleWTCEligibilityResponseExample.json
              example-4:
                description: The person is ineligible for Help to Save as they are entitled to WTC but not in receipt of positive WTC/CTC Tax Credit (nil TC) and in receipt of UC but their household income is insufficient
                value: !include examples/IneligibleWTCandUCEligibilityResponseExample.json
              example-5:
                description: The person is ineligible for Help to Save as they are not entitled to WTC and are in receipt of UC but their household income is insufficient
                value: !include examples/IneligibleUCIncomeInsufficientEligibilityResponseExample.json
              example-6:
                description: The person is ineligible for Help to Save as they are entitled to WTC but not in receipt of positive WTC/CTC Tax Credit (nil TC) and they are not in receipt of UC
                value: !include examples/IneligibleNotPositiveWTCAndNoUCEligibilityResponseExample.json
              example-7:
                description: The person is ineligible for Help to Save as they are not entitled to WTC and not in receipt of UC
                value: !include examples/IneligibleNoWTCNoUCEligibilityResponseExample.json
              example-8:
                description: The person already has a Help to Save account
                value: !include examples/AccountExistsEligibilityResponseExample.json

