#%RAML 1.0
title: Help-To-Save
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include docs/versioning.md
 - title: Parameters
   content: !include docs/parameters.md
 - title: E2E Live Support Journey Analysis
   content: !include docs/liveSupport.md
 - title: Errors
   content: !include docs/errors.md
 - title: Timeouts
   content: !include docs/timeouts.md
 - title: Data Transformations
   content: !include docs/dataTransformations.md
 - title: Access to the API
   content: !include docs/access.md
 - title: Diacritics and Legal Considerations
   content: !include docs/diacritics.md
 - title: Security Matters
   content: !include docs/security.md
 - title: Digitally Excluded Callers
   content: !include docs/digitallyExcluded.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/individuals/help-to-save/account:
  post:
    description: Sends a request to create an account on behalf of the user, noting the value fields below are all example values with the exception of fields Accept and Content-Type which should be presented as quoted string values as shown.
    is: [headers.acceptHeader, headers.contentHeader]
    securedBy: [ sec.x-application ]
    headers:
      gov-client-user-ID:
        example: EL079651A
        description: Applicant's NINO
      gov-client-timezone:
         example: UTC
         description: Timezone Abbreviation
      gov-vendor-version:
         example: "1.3"
         description: Gov Vendor Version
      gov-vendor-instance-ID:
         example: fa7c484c-d8cf-4f8a-a39c-54a2a4c04bc6
         description: Hashed value, unique to a specific installation of the vendor's software
    body:
      application/json:
        type: !include schemas/CreateAccount.json
        example: !include schemas/CreateAccountExample.json
    responses:
      201:
      400:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Bad request http response
            example: !include examples/ErrorResponseExample.json
      401:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Unauthorized http response
            example: !include examples/ErrorUnauthorizedResponseExample.json
      403:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Forbidden http response
            example: !include examples/ErrorForbiddenResponseExample.json
      404:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Not found http response
            example: !include examples/ErrorNotFoundResponseExample.json
      405:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Method not allowed http response
            example: !include examples/ErrorMethodNotAllowedResponseExample.json
      409:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Conflict http response
            example: !include examples/ErrorConflictResponseExample.json
      500:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Internal server error response
            example: !include examples/InternalServerErrorResponseExample.json
      502:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Bad gateway http repsonse
            example: !include examples/BadGatewayErrorResponseExample.json
      503:
        body:
          application/json:
            type: !include schemas/ErrorResponse.json
            description: Service unavailable http response
            example: !include examples/ServiceUnavailableErrorResponseExample.json